# Generated by Django 4.1 on 2022-08-23 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_user_profile_facebook_url_user_profile_github_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='others',
            new_name='linkedin_url',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='website_utl',
            new_name='website_url',
        ),
    ]
